# Site settings
title: Mike R. Gray
email: your-email@domain.com
description: ""
baseurl: ""
url: http://www.mikergray.com
twitter_username: realmikegray
github_username:  mikergray

# Build settings
markdown: kramdown
permalink: pretty
#paginate: 3
